apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: milowilo-app
        image: andreapeterson/milowilo-app
        resources:
          limits:
            memory: "1Gi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          name: myapp-port
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', "until nslookup db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
      - name: init-mymc
        image: busybox
        command: ['sh', '-c', "until nslookup cache.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mymc; sleep 2; done"]

        