apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: ebs.csi.aws.com 
metadata:
  name: csi-sc
parameters: 
  encrypted: "true"
  type: gp3
allowVolumeExpansion: true
volumeBindingMode: Immediate